### ISSUE TITLE
With the tenant context cannot get "role", "clusterrole"

### ISSUE THREAD

**Issue by vincent-pli** [kubewharf/kubezoo#9]
### What happened?

Follow the quick start, then hit the issue:
```
[root@experimental kubezoo]# kubectl get role --kubeconfig 111111.kubeconfig
Error from server: no table handler registered for this type *rbac.RoleList
[root@experimental kubezoo]# kubectl get clusterrole --kubeconfig 111111.kubeconfig
Error from server: no table handler registered for this type *rbac.ClusterRoleList
```

### What did you expect to happen?

At least get `No resources found in default namespace`

### How can we reproduce it (as minimally and precisely as possible)?

everytime

### Software version

<details>

```console
$ <software> version
# paste output here
```
</details>

**Comment by caohe** [comment]
Thanks for your feedback! We will check and get back to you as soon as possible.

**Comment by Silverglass** [comment]
@Silverglass
